server:
  port: 8081

spring:
  application:
    name: base-common
    version: 0.0.1-SNAPSHOT
    package: com.hongda.basecommon
  profiles:
      active: dev


  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


