<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <!--它继承了 Spring Boot 官方提供的 spring-boot-starter-parent 模块，
  这是一个 Spring Boot 应用的标准化父 POM，它的核心功能-->
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.5.5</version>
    <relativePath/>
  </parent>
  <groupId>com.hongda</groupId>
  <artifactId>base-common</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>base-common</name>
  <description>base-common</description>


  <properties>
    <!-- Site Project Version here -->
    <version.current>1.3.8</version.current>

    <!-- Standard properties -->
    <java.version>1.8</java.version>
    <maven.compiler.source>${java.version}</maven.compiler.source>
    <maven.compiler.target>${java.version}</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
  </properties>

  <dependencies>
    <!-- Spring -->
    <!--这是 Maven 的 <parent> 配置，用于指定当前项目的 父项目（Parent Project）-->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
    </dependency>

    <!--这是 Spring Boot 提供的 Web 开发核心模块，
    它封装了构建 Web 应用所需的所有基础依赖和自动配置，主要包括：-->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
      <scope>compile</scope>
    </dependency>

    <!--这是 阿里云官方提供的钉钉服务 SDK，用于在 Java 应用中快速集成钉钉开放平台的能力，-->
    <dependency>
      <groupId>com.aliyun</groupId>
      <artifactId>alibaba-dingtalk-service-sdk</artifactId>
      <version>2.0.0</version>
    </dependency>

    <!--这是 Spring Boot 提供的 面向切面编程（AOP）模块，它封装了 Spring AOP 和 AspectJ 的功能
    ，允许你在不修改业务代码的前提下，实现日志记录、权限控制、性能监控等功能。-->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-aop</artifactId>
      <scope>compile</scope>
    </dependency>

    <!--这是 Spring Boot 提供的一个用于 监控和管理应用程序的模块，它提供了一系列内置的端点（Endpoints）
    ，可以用来查看应用运行状态、健康状况、日志、配置等信息。-->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
      <scope>compile</scope>
    </dependency>

    <!--这是 Spring Boot 提供的一个 开箱即用的参数校验模块，它封装了 Java Bean Validation（JSR-380）规范，
    并默认使用 Hibernate Validator 实现。-->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-validation</artifactId>
      <scope>compile</scope>
    </dependency>
    <!--spring-cloud-loadbalancer 是 Spring Cloud 提供的客户端负载均衡器，用于在微服务架构中实现请求在多个实例之间的智能分发。-->
    <!--集成 OpenFeign 和 RestTemplate：-->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-redis</artifactId>
      <scope>provided</scope>
    </dependency>

    <!--属于 OpenFeign 原生库，提供了基本的 Feign 功能。-->
    <dependency>
      <groupId>io.github.openfeign</groupId>
      <artifactId>feign-core</artifactId>
      <version>10.12</version>
      <scope>compile</scope>
    </dependency>

  <!--这是 Spring Cloud 提供的 OpenFeign 的核心模块，
  用于在 Spring Boot 应用中实现声明式的 REST 客户端调用。-->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-openfeign-core</artifactId>
      <version>3.0.4</version>
      <scope>compile</scope>
    </dependency>

    <!--它是 Spring Cloud 提供的一个客户端负载均衡组件，
    用于在微服务架构中实现对多个服务实例之间的请求分发。-->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-loadbalancer</artifactId>
      <version>3.0.4</version>
      <optional>true</optional>
    </dependency>

    <!-- caffeine -->
    <!--该依赖是 Caffeine —— 一个高性能的 Java 缓存库，
    提供本地缓存能力，适用于需要快速访问、频繁读取但不频繁变更的数据。-->
    <dependency>
      <groupId>com.github.ben-manes.caffeine</groupId>
      <artifactId>caffeine</artifactId>
    </dependency>

    <!-- JMX logging -->
    <!--该依赖是 Jolokia 的核心模块，
    用于在 Java 应用中通过 HTTP 提供对 JMX（Java Management Extensions）
     的访问能力。-->
    <dependency>
      <groupId>org.jolokia</groupId>
      <artifactId>jolokia-core</artifactId>
    </dependency>

    <!--该依赖是 Logback 的扩展模块，用于将日志输出为 JSON 格式，
    并支持与 Logstash、Elasticsearch 和 Kibana（统称 ELK）集成，实现高效的日志采集、
    分析和可视化。-->
    <dependency>
      <groupId>net.logstash.logback</groupId>
      <artifactId>logstash-logback-encoder</artifactId>
      <version>7.0.1</version>
    </dependency>

    <!-- Lombok -->
    <!--它主要用来简化 POJO（Plain Old Java Object）类的开发，例如：
    自动生成 getter/setter
    自动生成 toString(), equals(), hashCode()
    自动生成构造方法
    支持 Builder 模式、日志注入等-->
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
    </dependency>

    <!-- Prometheus -->
   <!--用于将 Spring Boot 应用中的监控指标（如 JVM、HTTP 请求、缓存命中率等）
    以 Prometheus 可识别的格式暴露出来。-->
    <dependency>
      <groupId>io.micrometer</groupId>
      <artifactId>micrometer-registry-prometheus</artifactId>
    </dependency>

    <!-- InfluxDB -->
    <!--该依赖是 InfluxDB 的 Java 客户端库，
    用于在 Java 应用中与 InfluxDB（一个高性能的时间序列数据库）进行交互。-->
    <dependency>
      <groupId>org.influxdb</groupId>
      <artifactId>influxdb-java</artifactId>
    </dependency>


    <!-- Resubmit Cache https://github.com/jhalterman/expiringmap -->
    <!--该依赖是一个 轻量级的 Java 内存缓存库，用于创建带有 自动过期机制 的 Map 实现。-->
    <dependency>
      <groupId>net.jodah</groupId>
      <artifactId>expiringmap</artifactId>
      <version>0.5.10</version>
    </dependency>

    <!-- Gaia Toolkit -->
    <!--集合工具类扩展（如 ImmutableList, Multimap）
    字符串处理（如 Strings, Splitter, Joiner）
    缓存实现（如 CacheBuilder）
    函数式编程支持（如 Function, Predicate）
    异常封装、文件操作、事件总线等”-->
    <dependency>
      <groupId>com.xpp.gaia</groupId>
      <artifactId>gaia-toolkit</artifactId>
      <version>[0.0.1,)</version>
    </dependency>

    <!-- Mybatis Plus -->
    <!--这是 MyBatis-Plus 的代码生成器（Code Generator），用于快速自动生成基于数据库表结构的
     Java 实体类、Mapper 接口、Service 层、Controller 层等代码，极大提升开发效率。-->
    <dependency>
      <groupId>com.baomidou</groupId>
      <artifactId>mybatis-plus-generator</artifactId>
      <version>3.5.1</version>
    </dependency>

  <!--用于简化 MyBatis 在 Spring Boot 项目中的集成和使用。
  它封装了 MyBatis 的核心功能，并提供了一系列增强特性，使得数据库操作更加高效简洁。-->
    <dependency>
      <groupId>com.baomidou</groupId>
      <artifactId>mybatis-plus-boot-starter</artifactId>
      <version>3.4.3.4</version>
      <scope>provided</scope>
    </dependency>

    <!--该依赖是 MyBatis 的分页插件，用于简化数据库查询的分页操作。
    它通过拦截 MyBatis 的 SQL 查询语句，在执行时自动加上分页逻辑（如 LIMIT offset, size），实现对结果集的分页处理。-->
    <dependency>
      <groupId>com.github.pagehelper</groupId>
      <artifactId>pagehelper</artifactId>
      <version>5.3.0</version>
      <scope>provided</scope>
    </dependency>

    <!--引入 Apache Velocity 模板引擎，用于动态生成文本内容（如 HTML 页面、邮件模板、配置文件等）。
     支持通过 Java 对象与模板结合渲染输出，适用于需要动态内容渲染的场景。-->
    <dependency>
      <groupId>org.apache.velocity</groupId>
      <artifactId>velocity-engine-core</artifactId>
      <version>2.3</version>
    </dependency>

    <!--引入 H2 数据库，这是一个轻量级的 Java 嵌入式数据库。
     支持内存模式和磁盘存储模式，适合用于开发、测试环境或小型应用中。-->
    <dependency>
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
    </dependency>

    <!-- Doc -->
    <!--提供了一个基于 Swagger 的增强 UI 界面（Knife4j），用于展示和测试 Spring Boot 项目中的 RESTful API 接口。
    支持接口文档自动生成，包括参数、返回值、示例请求等信息。
    支持 OAuth2 认证调试、离线文档导出、多语言支持等功能。
    集成简单，只需引入 starter 即可自动配置。-->
    <dependency>
      <groupId>com.github.xiaoymin</groupId>
      <artifactId>knife4j-spring-boot-starter</artifactId>
      <version>2.0.7</version>
    </dependency>

    <!-- Jedis -->
    <!--此依赖提供了以下功能：
    连接和操作 Redis 数据库（字符串、哈希、列表、集合等数据结构）
    支持连接池管理（如使用 JedisPool 提高性能）
    支持 Redis 单机、哨兵、集群等多种部署模式
    支持 Lua 脚本执行、事务控制等高级功能
    适用于项目中需要缓存、消息队列、分布式锁等场景。-->
    <dependency>
      <groupId>redis.clients</groupId>
      <artifactId>jedis</artifactId>
      <version>4.0.1</version>
    </dependency>

    <!-- Xxl Job
     此依赖用于支持与 XXL-JOB 调度中心进行交互，包括：
    注册执行器到调度中心
    接收调度中心下发的任务
    执行定时任务逻辑
    上报任务执行状态和日志
    适用于微服务架构中需要实现分布式的任务调度场景，如数据同步、定时清理、报表生成等-->
    <dependency>
      <groupId>com.xuxueli</groupId>
      <artifactId>xxl-job-core</artifactId>
      <version>2.3.0</version>
      <scope>provided</scope>
    </dependency>

    <!-- google
  Google Guava 提供了许多增强 Java 开发的功能，例如：
    集合工具类扩展（如 ImmutableList, Multimap）
    字符串处理（如 Strings, Splitter, Joiner）
    缓存实现（如 CacheBuilder）
    函数式编程支持（如 Function, Predicate）
    异常封装、文件操作、事件总线等-->
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>30.1-jre</version>
      <scope>provided</scope>
    </dependency>

    <!-- files  该依赖用于提供与文件处理相关的 API 接口定义。
    它允许当前项目通过这些接口调用外部文件服务的通用功能，例如上传、下载等操作-->
    <dependency>
      <groupId>com.xpp.iaas</groupId>
      <artifactId>xpp-iaas-file</artifactId>
      <version>0.0.2-RELEASE</version>
      <classifier>api</classifier>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <scope>test</scope>
    </dependency>

  </dependencies>

  <build>
    <!--文件名字-->
    <finalName>${project.artifactId}</finalName>
    <plugins>
      <!--编译 Java 源代码-->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
      </plugin>
      <!--在执行 mvn package 命令时，自动将当前项目的源代码打包成一个 .jar 文件。-->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <executions>
          <!--表示这个插件会在 mvn package 生命周期阶段执行-->
          <execution>
            <id>attach-sources</id>
            <phase>package</phase>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <!-- 分环境打包: y/n -->
  <profiles>
    <profile>
      <id>dev</id>
      <properties>
        <version.final>${version.current}-SNAPSHOT</version.final>
        <repository.id>${project.distributionManagement.snapshotRepository.id}</repository.id>
        <repository.url>${project.distributionManagement.snapshotRepository.url}</repository.url>
      </properties>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
    </profile>
    <!--mvn clean package -Ptest-->
    <profile>
      <id>test</id>
      <properties>
        <version.final>${version.current}-RELEASE</version.final>
        <repository.id>${project.distributionManagement.repository.id}</repository.id>
        <repository.url>${project.distributionManagement.repository.url}</repository.url>
      </properties>
    </profile>
    <profile>
      <id>prod</id>
      <properties>
        <version.final>${version.current}-RELEASE</version.final>
        <repository.id>${project.distributionManagement.repository.id}</repository.id>
        <repository.url>${project.distributionManagement.repository.url}</repository.url>
      </properties>
    </profile>
  </profiles>

  <!--把自己打包jar上传的仓库-->
  <!-- 分环境打包: y/n -->
  <!--上传jar到仓库：打包后根据不同的环境，把当前项目jar,上传仓库的不同位置-->
  <distributionManagement>
    <!--正式：如果你的项目版本是：0.0.1-RELEASE 或 0.0.1（没有 SNAPSHOT），则使用 <repository> 地址。-->
    <repository>
      <id>releases</id>
      <url>${nexus.location}/nexus/content/repositories/releases</url>
    </repository>
    <!--开发：果你的项目版本是：0.0.1-SNAPSHOT，则使用 <snapshotRepository> 配置的地址；-->
    <snapshotRepository>
      <id>snapshots</id>
      <url>${nexus.location}/nexus/content/repositories/snapshots</url>
    </snapshotRepository>
  </distributionManagement>


  <!--下载jar-->
  <!--优先使用pom配置的仓库地址下载；如果没有配置就从setting.xml中配置的镜像配置的地址下载-->
  <!--如果仓库有账号和密码；他在setting中的server标签配置；id数据一样作为绑定-->
  <!--作用：告诉 Maven 去哪下载依赖（jar 包）-->
  <!--私有库需要Nexus平台搭建-->
  <!--私有仓库里的 jar 主要来自你们自己的项目构建产物，也可以是手动上传的第三方依赖，或者是代理远程仓库缓存下来的依赖。-->
  <repositories>
    <repository>
      <!--true:Maven 会定期从 Nexus 等仓库拉取最新的 SNAPSHOT 版本-->
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <!--该仓库的唯一标识符，通常与 settings.xml 中的 <server> 对应-->
      <id>nexus</id>
      <!--仓库名称，仅供展示使用-->
      <name>Public Repositories</name>
      <!--仓库地址，${nexus.location} 是一个变量，在 <properties> 中定义为 http://10.0.3.31:8084，最终指向 Nexus 私有仓库地址-->
      <url>${nexus.location}/nexus/content/groups/public</url>
    </repository>
  </repositories>

</project>
